## MARK: - Project Name
name: HealthHouse


## MARK: - Configs Section
configs:
    DEV-Debug   : debug
    DEV-Release : release
    STA-Debug   : debug
    STA-Release : release
    PRO-Debug   : debug
    PRO-Release : release

## MARK: - Option Section
options:
    xcodeVersion             : '12.4'
    deploymentTarget         : '13.0'
    groupSortPosition        : down
    generateEmptyDirectories : true
    minimumXcodeGenVersion   : '2.18.0'
    preGenCommand            : ./pregencommand.sh
    postGenCommand           : pod install

## MARK: - Target Section
targets:
    HealthHouse:
        type: application
        platform: iOS
        sources: HealthHouse
        settings:
            base:
                CODE_SIGN_STYLE: Automatic
                DEVELOPMENT_TEAM: 5U7M39KWXM # Arif Luthfiansyah - Personal Team (lutluthfi@icloud.com)
                EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
                IPHONEOS_DEPLOYMENT_TARGET: 13.0
                INFOPLIST_FILE: HealthHouse/Resources/Info.plist
                MOMC_NO_WARNINGS: true
                TARGETED_DEVICE_FAMILY: 1
            configs:
                DEV-Debug:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.dev
                    PRODUCT_BUNDLE_IDENTIFIER: com.arlt.healthhouse.dev
                    PRODUCT_NAME: Health House
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV
                DEV-Release:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.dev
                    PRODUCT_BUNDLE_IDENTIFIER: com.arlt.healthhouse.dev
                    PRODUCT_NAME: Health House
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV
                STA-Debug:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.sta
                    PRODUCT_BUNDLE_IDENTIFIER: com.arlt.healthhouse.sta
                    PRODUCT_NAME: Health House
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: STA
                STA-Release:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.sta
                    PRODUCT_BUNDLE_IDENTIFIER: com.arlt.healthhouse.sta
                    PRODUCT_NAME: Health House
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: STA
                PRO-Debug:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.pro
                    PRODUCT_BUNDLE_IDENTIFIER: com.arlt.healthhouse
                    PRODUCT_NAME: Health House
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: PRO
                PRO-Release:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.pro
                    PRODUCT_BUNDLE_IDENTIFIER: com.arlt.healthhouse
                    PRODUCT_NAME: Health House
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: PRO
        info:
            path: HealthHouse/Resources/Info.plist
            properties:
                CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
                CFBundleExecutable: $(EXECUTABLE_NAME)
                CFBundleInfoDictionaryVersion: 6.0
                CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
                CFBundleShortVersionString: 1.0.0
                CFBundleVersion: "1"
                LSRequiresIPhoneOS: true
                UIApplicationSceneManifest:
                    UIApplicationSupportsMultipleScenes: false
                    UISceneConfigurations:
                        UIWindowSceneSessionRoleApplication:
                            - UISceneConfigurationName: Default Configuration
                              UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                              UISceneStoryboardFile: LaunchScreen
                UIApplicationSupportsIndirectInputEvents: true
                UILaunchStoryboardName: LaunchScreen
                UIMainStoryboardFile: LaunchScreen
                UIRequiredDeviceCapabilities:
                    - armv7
                UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
                UIUserInterfaceStyle: Light
                NSDocumentsFolderUsageDescription: $(PRODUCT_NAME) will helps you to manage your health attachment
                NSDownloadsFolderUsageDescription: $(PRODUCT_NAME) will helps you to manage your health attachment
                NSLocationAlwaysAndWhenInUseUsageDescription: $(PRODUCT_NAME) will helps you to remember and find your hospital
                NSLocationWhenInUseUsageDescription: $(PRODUCT_NAME) will helps you to remember and find your hospital
                NSPhotoLibraryUsageDescription: $(PRODUCT_NAME) will helps you to detail your activity by attaching a photo as an attachment
    HealthHouseTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: HealthHouseTests
        settings:
            MOMC_NO_WARNINGS: true
            INFOPLIST_FILE: HealthHouseTests/Info.plist
            TEST_TARGET_NAME: HealthHouse
            TEST_HOST: $(BUILT_PRODUCTS_DIR)/Health House.app/Health House

## MARK: - Scheme Section
schemes:
    DEV-HealthHouse:
        build:
            targets:
                HealthHouse: [run, archive]
        run:
            config: DEV-Debug
        test:
            config: DEV-Debug
        profile:
            config: DEV-Release
        analyze:
            config: DEV-Debug
        archive:
            config: DEV-Release
            customArchiveName: DEV HealthHouse
            revealArchiveInOrganizer: true
    PRO-HealthHouse:
        build:
            targets:
                HealthHouse: [run, archive]
        run:
            config: PRO-Debug
        test:
            config: PRO-Debug
        profile:
            config: PRO-Release
        analyze:
            config: PRO-Debug
        archive:
            config: PRO-Release
            customArchiveName: PRO HealthHouse
            revealArchiveInOrganizer: true
